
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yybospaazevrtngcpbmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Ym9zcGFhemV2cnRuZ2NwYm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzU1MTEsImV4cCI6MjA1OTgxMTUxMX0.vEP04S74Ywbndo1U1x26VpGI99AMTIsi9kXIbIpXMAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
